name:Ola, mundo

on: [push]

jobs:
  ola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
    steps:
      - name: Ola, mundo
        run: echo "Ola, mundo!"